services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  data_ingest:
    build:
      context: .
      dockerfile: services/data_ingest/Dockerfile
    env_file: .env
    depends_on:
      - redis

  normalize_enrich:
    build:
      context: .
      dockerfile: services/normalize_enrich/Dockerfile
    env_file: .env
    depends_on:
      - redis
      - data_ingest

  signal_detect:
    build:
      context: .
      dockerfile: services/signal_detect/Dockerfile
    env_file: .env
    depends_on:
      - redis
      - normalize_enrich

  alert_engine:
    build:
      context: .
      dockerfile: services/alert_engine/Dockerfile
    env_file: .env
    depends_on:
      - redis
      - signal_detect
    tty: true

volumes:
  redis_data:
